# Generated by Django 5.0.6 on 2024-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserThread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_user_id', models.CharField(max_length=128)),
                ('openai_thread_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
